INCLUDE_DIRS := ./
CC 		:= g++
CFLAGS 		 := -I$(INCLUDE_DIRS)

make: class_template.cpp customErrorClass.cpp
	$(CC) -g -o Garza_CodeChallengeOne class_template.cpp customErrorClass.cpp $(CFLAGS)

clean:
	rm Garza_CodeChallengeOne